### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by JossWhittle** [rosalindfranklininstitute/LeopardGecko#1]
Hi Luis, my main feedback is to take the opportunity now while the project structure is manageable to put it into a project structure that will scale nicely as you add things going forward. 

---
## Restructure project into an installable package and set of user scripts

```
/
    README.md
    LICENSE
    setup.py
    Dockerfile

    .github/
        workflows/
            ci.yml

    src/
        LeopardGecko/
            __init__.py

            some_sub_package/
                __init__.py
                some_class.py
                some_other_class.py
  
    tests/
        __init__.py

        some_sub_package/
            __init__.py
            test_some_class.py
            test_some_other_class.py

    scripts/
        lg-genpredcsreport.py
```

---
## Use a `setup.py` to install dependencies automatically

Example which uses the above structure: 
https://github.com/JossWhittle/Opt-ID/blob/development-r3.0-jax-core/setup.py

When you `pip install -e .` from the root repo directory, `setup.py` will force pip to install the packages listed in the `install_requires=[ ... ]` array.

---
## In `tests/` and `scripts/` import `LeopardGecko` as if it is an external package installed with `pip`

Within the `src` directory you should use relative import statements. In the file `src/LeopardGecko/some_sub_package/some_class.py` it might refer to `some_other_class.py` by stating `from .some_other_class import SomeOtherClass`. But when calling the same class from the `tests/` or `scripts/` directory you would write `from LeopardGecko.some_sub_package import SomeOtherClass`.

This ensures that your tests and scripts only ever use the version of your library that is correctly installed via pip, and prevents the possibility of python accidently detecting another python file with the same name in the local directory.

---
## Use Continuous Integration through Github Actions automatically run unit tests and build/push Docker images

Example CI script:
https://github.com/JossWhittle/Opt-ID/blob/development-r3.0-jax-core/.github/workflows/ci.yml

This script creates and pushes an up to date versions of the Docker image to Dockerhub for each branch in your repository. 

For my master branch I get two images `josswhittle/opt-id:env` and `josswhittle/opt-id:latest` where `env` is an image with all the dependencies needed, and `latest` is based on `env` and also has my library pip installed on top of it.

For the development branch I also get `josswhittle/opt-id:env-development` and `josswhittle/opt-id:development` which represent the current state of that branch. 

The core unit test command is:
```
python -m pytest --cov=src tests/ --cov-report xml:coverage.xml --cov-report term-missing
```

Code coverage is transmitted to https://codecov.io which requires you to enable that service for your Github repo.

---
## Parsing command line arguments:

https://github.com/rosalindfranklininstitute/LeopardGecko/blob/4be0fbc20df9b22fd3782e5e5f05160b1223d8e3/lg-genpredcsreport.py#L79-L90

Rather than hardcoding a dict to extract the parsed arguments you can use `configuration = vars(args)` to extract all arguments as a dict directly.
Example: https://stackoverflow.com/a/28546857

---
## Use subprocess.POpen instead of os.system or use the python APIs provided by jupyter directly from within python

https://github.com/rosalindfranklininstitute/LeopardGecko/blob/4be0fbc20df9b22fd3782e5e5f05160b1223d8e3/lg-genpredcsreport.py#L108

**Comment by tschoonj** [comment]
That is a great review Joss! This should be seen by everybody @LAShemilt @DimitriosBellos @MasterVexillen @N-Lin 

Some more comments from me:

1. Use `setup.cfg` and `pyproject.toml` to be compatible with PEP 517 and 518. For an example look at the [rfi-file-monitor](https://github.com/rosalindfranklininstitute/rfi-file-monitor). `setup.py` should be almost empty and contain nothing but the call to `setup()`.
2. Use `subprocess.run` instead of `subprocess.Popen`, which is easier to use.
3. You can also use CI to automatically [upload releases](https://github.com/rosalindfranklininstitute/rfi-file-monitor/blob/master/.github/workflows/publish-to-pypi.yml) to PyPI.

**Comment by perdigao1** [comment]
wow. That was a great review. Clearly I was not following the best coding standards. I don't want to be victimised like Neil Fergusson group was when they released their code. Any comments on the actual code and functionality is also welcome.

**Comment by JossWhittle** [comment]
Still need to make the Opt-ID repo compatible with PEP 517 and 518, really nice to see a concrete example from the rfi-file-monitor for how to do it so cheers, Tom!

**Comment by LAShemilt** [comment]
Really nice and clear Joss. We should probably turn this into a template document to follow. Thanks for the putting in the time.

**Comment by MasterVexillen** [comment]
Really nice review Joss! Thanks for giving such a good demonstration of what code reviews should look like!

**Comment by perdigao1** [comment]
I finally got some time to implement some of the changes suggested. I am now organising the directory structure and I will work next in producing a setup.py and docker container file.

As with folder structure in `/src`, I will for now not introduce `/subpackages` folders because I have all the code in a single file. This is in purpose to simplify its usage with a single import statement, like import `leopardgecko as lg` . There is probably a way to achieve this but for now it is not needed and I may risk breaking the code.

I also had a deep thought on your suggestion about the "Parsing the command line arguments". This file does parse command line arguments but this line

```
configuration =  {"datafilename" : args.datafilename , \ 
     "outputfilepdf" : outputfile , \ 
     "avgpwidth" : args.avgpwidth ,\ 
     "avgpkwidth" : args.avgpkwidth , \ 
     "avgpstride" : args.avgpstride , \ 
     "avgpforcerecalc" : args.avgpforcerecalc, \ 
     "csweightingmethod" : args.csweightingmethod, \ 
     "csvolscalculatefile" : args.csvolscalculatefile , \ 
     "csroimethod" : args.csroimethod , 
     "dataoutfolder" : args.dataoutfolder, \ 
     "dosdccalculation": args.dosdccalculation \ 
 } 
```

... is intended to create a configuration file for the jupyter notebook that will then generate a report. The jupyter notebook is `lg-genpredcsreport.ipynb` , and inside it we need to make sure it reads the parameters with exactly the same labels. If I do  `configuration = vars(args)` , and then save as a .yaml file, then there is a risk that the dict has different labels and may stop working. So for now I will retain this part as it is and add a comment stating that this line must be "compatible" with the settings read by the jupyter notebook.

Regarding the subprocess.POpen or subprocess.run, instead of os.system(cmd),  I don't quite understand why this is better. Is it becuase it is advised as replacement?


Also, I am not sure what jupyter API you refer to. As far as I know this command is the way I know  to generate a pdf report from a running jupyter notebook, and this API is quite limited, partly because we cannot specify the output pdf filename.
`"jupyter nbconvert --no-input --execute --to pdf " + notebookfile`

**Comment by tschoonj** [comment]
the main reason to use `subprocess.Popen/run` over `os.system` is that it allows you to do a lot more with the spawned process: you can get its stdout and stderr afterwards into Python variables that you can use afterwards, and you can pipe into stdin if that were necessary. `os.system` just dumps all generated output to the console.

Putting all your code into a single `__init__.py` file is for now probably fine, but you should start splitting up into multiple files if it becomes too long. It should still be possible to access their classes and methods from the main `__init__.py` module, as long as they are imported in there.

**Comment by JossWhittle** [comment]
Splitting your code up into a hierarchy still allows you to import it all through a common root import. 

For example, consider the sub-hierarchy:
https://github.com/JossWhittle/Opt-ID/blob/development-r3.0-jax-core/src/optid/__init__.py
https://github.com/JossWhittle/Opt-ID/blob/development-r3.0-jax-core/src/optid/bfield/__init__.py
https://github.com/JossWhittle/Opt-ID/blob/development-r3.0-jax-core/src/optid/bfield/bfield.py

The main package is imported as `import optid` or `import optid as op`. The subpackage bfield is available at `op.bfield` and contains a class Bfield `op.bfield.Bfield` which is technically implemented at `op.bfield.bfield.Bfield` but is referenced in `bfield/__init__.py` so that it is directly part of the the `op.bfield` namespace. 

The `__init__.py` files are used to specify what public facing structure for your library / API should be exposed to the user programmer. The `foobar.py` files are where you put the actual implementations so that each class can have its own file / responsibilities. 

It's easiest to adopt such a structure earlier in the development process, otherwise you will need to do a lot of refactoring to migrate later. It also means you can write your unit tests mirroring the same hierarchy of sub-package structures which makes them easy to maintain and debug. 

---

Your calls to `parser.add_argument(...)` to specify which parameters are valid and what types / validation checks they require means that `configuration = vars(args)` will always end up with the same keys as the ones you asked for. 

---

Using the subprocess package for calling external programs means you know whether they succeed or not, and prevents your code from blindly continuing regardless of whether an error occurred in the external program.

**Comment by perdigao1** [comment]
Thank you. That is a lot of bfield-help!
